### ISSUE TITLE
python 3.11 compatible?

### ISSUE THREAD

**Issue by IcelandicCenterArtificialIntelligence** [neverbiasu/ComfyUI-SAM2#15]
Cannot install this as the hydra module won't install, it complains about longintrepr.h
Can you confirm if it's 3.11 compatible?

**Comment by neverbiasu** [comment]
[SAM2 ](https://github.com/facebookresearch/segment-anything-2) said the code requires python>=3.10, I'll check it later.

**Comment by Hujikuio** [comment]
`
Traceback (most recent call last):
  File "C:\Hello\Github\ComfyUI\nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Hello\Github\ComfyUI\custom_nodes\ComfyUI-SAM2\__init__.py", line 1, in <module>
    from .node import SAM2ModelLoader, GroundingDinoModelLoader, GroundingDinoSAM2Segment, InvertMask, IsMaskEmptyNode
  File "C:\Hello\Github\ComfyUI\custom_nodes\ComfyUI-SAM2\node.py", line 15, in <module>
    from sam2.build_sam import build_sam2
  File "C:\Hello\Github\ComfyUI\custom_nodes\ComfyUI-SAM2\sam2\__init__.py", line 7, in <module>
    from hydra import initialize_config_module
ModuleNotFoundError: No module named 'hydra'
`

requirements.txt:

`
timm
addict
yapf
numpy<2
tqdm>=4.66.1
hydra-core>=1.3.2
iopath>=0.1.10
pillow>=9.4.0
matplotlib>=3.9.1
opencv-python>=4.7.0
`
